stages:
- stage: Build
  jobs:
  - job: Build
    pool: 'Hosted VS2017'
    steps:
    - script: echo 'Build'

- stage: Environment
  jobs:
  - job: Test
    pool: 'Hosted VS2017'
    steps:
    - script: echo 'Hosted'
    - task: NuGetToolInstaller@0
  - deployment: DeployPPE
    environment: test_env
    pool: 'Hosted VS2017'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

- stage: ServiceEndpoint
  jobs:
  - job: DeployProd
    pool: 'Hosted VS2017'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment'
      inputs:
        azureSubscription: test_con
        action: Start
        resourceGroupName: 'rg'
