stages:
- stage: ServiceEndpoint
  jobs:
  - job: DeployProd
    pool: 'Hosted VS2017'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Start action on ankhokha-RG'
      inputs:
        azureSubscription: Git connection 1
        action: Start
        resourceGroupName: 'vamwg'
